version: "3.9"

services:
  n8n-playwright:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: n8n-playwright-stable
    restart: unless-stopped

    ports:
      - "5680:5678"

    environment:
      # --- N8N Core ---
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_FOLDER=/opt/n8n
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false

      # --- Task Runners ---
      - N8N_RUNNERS_ENABLED=false

      # --- Code node allowances ---
      - NODE_FUNCTION_ALLOW_EXTERNAL=playwright-core,axios,lodash,moment,cheerio,ws
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false

      # --- Playwright ---
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true
      # Asegúrate en tu Dockerfile de usar playwright-core@1.55.0 para empatar con el server

      # --- System ---
      - TZ=America/Bogota
      - NODE_OPTIONS=--max-old-space-size=4096
      - NODE_ENV=production

      # --- Logging ---
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console

    volumes:
      - n8n_data:/opt/n8n
      - /dev/shm:/dev/shm:rw

    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: 2gb

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    networks:
      - n8n-network

volumes:
  n8n_data:
    driver: local

networks:
  n8n-network:
    external: true
    name: n8n-network
