version: "3.9"

services:
  playwright-server:
    # Usar versión más estable
    image: mcr.microsoft.com/playwright:v1.56.0-noble
    container_name: playwright-browser-server
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - TZ=America/Bogota
      - NODE_ENV=production
      - DEBUG=pw:browser*

    init: true
    ipc: host
    user: pwuser
    working_dir: /home/pwuser
    shm_size: 2gb

    command: >
      sh -c "
      echo '🎭 Playwright Server (Stable Version)';
      echo 'Starting on port 3000...';
      npx -y playwright@1.56.0 run-server --port 3000 --host 0.0.0.0
      "

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ -o /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

    networks:
      - n8n-network  # <-- misma red externa que usará el otro compose

networks:
  n8n-network:
    external: true   # <-- esta red debe existir: docker network create n8n-network
